package discovery

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestDeriveTitleFromText(t *testing.T) {
	tests := []struct {
		name string
		in   string
		want string
	}{
		{
			// Real openers carry <command-message> *and* <command-name>; the
			// synthetic single-tag shape hides the duplication bug that a
			// tag-only strip would introduce.
			name: "slash command with vault path args",
			in:   "<command-message>ryane-skills:ship-task</command-message>\n<command-name>/ryane-skills:ship-task</command-name>\n<command-args>Areas/dotfiles/Research agent-browser for cobalt.md</command-args>",
			want: "Research agent-browser for cobalt",
		},
		{
			// stripXMLTags removes <command-name> and <command-message> with
			// their content, so a no-args command leaves nothing at all. The
			// sentinel is the honest answer: the session carries no topic.
			name: "slash command with no args yields the sentinel",
			in:   "<command-message>org-task</command-message>\n<command-name>/org-task</command-name>\n<command-args></command-args>",
			want: "(no title)",
		},
		{
			name: "bare vault path",
			in:   "Areas/dotfiles/Retire cesium atticd SQLite database.md",
			want: "Retire cesium atticd SQLite database",
		},
		{
			name: "plain prose is returned as-is",
			in:   "openssl command to view https cert details",
			want: "openssl command to view https cert details",
		},
		{
			name: "typo in path is preserved, not corrected",
			in:   "<command-message>org-task</command-message>\n<command-name>/org-task</command-name>\n<command-args>gAreas/Org/Syncthing conflict watch - week 3 check.md</command-args>",
			want: "Syncthing conflict watch - week 3 check",
		},
		{
			name: "empty input yields the no-title sentinel",
			in:   "",
			want: "(no title)",
		},
		{
			name: "whitespace is collapsed",
			in:   "a   b\n\nc",
			want: "a b c",
		},
		{
			name: "system reminders are stripped",
			in:   "<system-reminder>noise</system-reminder>real message",
			want: "real message",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := DeriveTitleFromText(tt.in); got != tt.want {
				t.Errorf("DeriveTitleFromText(%q) = %q, want %q", tt.in, got, tt.want)
			}
		})
	}
}

func TestDeriveTitleFromText_TruncatesOnWordBoundary(t *testing.T) {
	// Byte 80 of this fixture falls mid-word ("charac|ter"), so a naive cut
	// would split it. The word-boundary rule must back up to the space.
	long := "this is a very long first message that goes well past the eighty character limit and keeps going"
	got := DeriveTitleFromText(long)

	if len(got) > maxTitleLen+3 {
		t.Errorf("title too long: %d bytes, %q", len(got), got)
	}
	if !strings.HasSuffix(got, "...") {
		t.Errorf("expected ellipsis suffix, got %q", got)
	}
	trimmed := strings.TrimSuffix(got, "...")
	if strings.HasSuffix(trimmed, " ") {
		t.Errorf("trailing space before ellipsis: %q", got)
	}
	// The cut must not leave a partial word.
	if !strings.HasSuffix(trimmed, "character") {
		t.Errorf("expected the cut to back up to a word boundary, got %q", got)
	}
}

func TestDeriveTitleFromText_ShortTitleNotTruncated(t *testing.T) {
	if got := DeriveTitleFromText("short one"); got != "short one" {
		t.Errorf("expected %q, got %q", "short one", got)
	}
}

func TestExtractFirstUserMessageRaw_SkipsCaveatPreamble(t *testing.T) {
	// Real sessions often open with a <local-command-caveat> block, which
	// stripXMLTags removes entirely. Returning it verbatim shadows the actual
	// opener on the next line, which is where the topic lives — 509 sessions
	// in the live archive have exactly this shape.
	dir := t.TempDir()
	path := filepath.Join(dir, "s.jsonl")
	lines := []string{
		`{"type":"user","message":{"content":"<local-command-caveat>Caveat: The messages below were generated by the user while running local commands.</local-command-caveat>"}}`,
		`{"type":"user","message":{"content":"<command-name>/org-task</command-name>\n<command-args>Areas/dotfiles/Remove starship nixpkgs workaround.md</command-args>"}}`,
	}
	if err := os.WriteFile(path, []byte(strings.Join(lines, "\n")+"\n"), 0o644); err != nil {
		t.Fatal(err)
	}

	if got := DeriveTitle(path); got != "Remove starship nixpkgs workaround" {
		t.Errorf("caveat preamble shadowed the real opener: got %q", got)
	}
}

func TestExtractFirstUserMessageRaw_CaveatOnlyStillReturnsSentinel(t *testing.T) {
	// A session that truly carries nothing but the caveat must still yield the
	// sentinel rather than the caveat text.
	dir := t.TempDir()
	path := filepath.Join(dir, "s.jsonl")
	line := `{"type":"user","message":{"content":"<local-command-caveat>Caveat: generated while running local commands.</local-command-caveat>"}}`
	if err := os.WriteFile(path, []byte(line+"\n"), 0o644); err != nil {
		t.Fatal(err)
	}

	if got := DeriveTitle(path); got != noTitle {
		t.Errorf("expected %q, got %q", noTitle, got)
	}
}
